# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify.ui'
#
# Created: Sat Feb 23 15:23:32 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_EditDlg(object):
    def setupUi(self, EditDlg):
        EditDlg.setObjectName(_fromUtf8("EditDlg"))
        EditDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        EditDlg.resize(409, 357)
        EditDlg.setSizeGripEnabled(False)
        EditDlg.setModal(True)
        self.label = QtGui.QLabel(EditDlg)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.editID = QtGui.QTextEdit(EditDlg)
        self.editID.setGeometry(QtCore.QRect(130, 20, 261, 21))
        self.editID.setAcceptDrops(True)
        self.editID.setAutoFillBackground(False)
        self.editID.setFrameShape(QtGui.QFrame.NoFrame)
        self.editID.setFrameShadow(QtGui.QFrame.Raised)
        self.editID.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editID.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editID.setReadOnly(True)
        self.editID.setObjectName(_fromUtf8("editID"))
        self.label_2 = QtGui.QLabel(EditDlg)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.editName = QtGui.QTextEdit(EditDlg)
        self.editName.setGeometry(QtCore.QRect(130, 50, 261, 21))
        self.editName.setAcceptDrops(True)
        self.editName.setAutoFillBackground(False)
        self.editName.setFrameShape(QtGui.QFrame.StyledPanel)
        self.editName.setFrameShadow(QtGui.QFrame.Sunken)
        self.editName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editName.setObjectName(_fromUtf8("editName"))
        self.editType = QtGui.QTextEdit(EditDlg)
        self.editType.setGeometry(QtCore.QRect(130, 80, 261, 21))
        self.editType.setAcceptDrops(True)
        self.editType.setAutoFillBackground(False)
        self.editType.setFrameShape(QtGui.QFrame.StyledPanel)
        self.editType.setFrameShadow(QtGui.QFrame.Sunken)
        self.editType.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editType.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editType.setObjectName(_fromUtf8("editType"))
        self.label_3 = QtGui.QLabel(EditDlg)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(EditDlg)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.editPrice = QtGui.QTextEdit(EditDlg)
        self.editPrice.setGeometry(QtCore.QRect(130, 140, 261, 21))
        self.editPrice.setAcceptDrops(True)
        self.editPrice.setAutoFillBackground(False)
        self.editPrice.setFrameShape(QtGui.QFrame.StyledPanel)
        self.editPrice.setFrameShadow(QtGui.QFrame.Sunken)
        self.editPrice.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editPrice.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editPrice.setObjectName(_fromUtf8("editPrice"))
        self.editPic = QtGui.QTextEdit(EditDlg)
        self.editPic.setGeometry(QtCore.QRect(130, 170, 181, 21))
        self.editPic.setAcceptDrops(True)
        self.editPic.setAutoFillBackground(False)
        self.editPic.setFrameShape(QtGui.QFrame.StyledPanel)
        self.editPic.setFrameShadow(QtGui.QFrame.Sunken)
        self.editPic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editPic.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editPic.setReadOnly(True)
        self.editPic.setObjectName(_fromUtf8("editPic"))
        self.label_5 = QtGui.QLabel(EditDlg)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(EditDlg)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 71, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.editTime = QtGui.QDateTimeEdit(EditDlg)
        self.editTime.setGeometry(QtCore.QRect(130, 270, 261, 31))
        self.editTime.setReadOnly(True)
        self.editTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.editTime.setDisplayFormat(_fromUtf8("yyyy-MM-dd hh:mm:ss"))
        self.editTime.setObjectName(_fromUtf8("editTime"))
        self.btnOk = QtGui.QPushButton(EditDlg)
        self.btnOk.setGeometry(QtCore.QRect(20, 310, 151, 31))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.btnExit = QtGui.QPushButton(EditDlg)
        self.btnExit.setGeometry(QtCore.QRect(220, 310, 151, 31))
        self.btnExit.setDefault(True)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.editComments = QtGui.QTextEdit(EditDlg)
        self.editComments.setGeometry(QtCore.QRect(130, 200, 261, 61))
        self.editComments.setAcceptDrops(True)
        self.editComments.setAutoFillBackground(False)
        self.editComments.setFrameShape(QtGui.QFrame.StyledPanel)
        self.editComments.setFrameShadow(QtGui.QFrame.Sunken)
        self.editComments.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editComments.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editComments.setObjectName(_fromUtf8("editComments"))
        self.label_7 = QtGui.QLabel(EditDlg)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 71, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.btnChooser = QtGui.QPushButton(EditDlg)
        self.btnChooser.setGeometry(QtCore.QRect(320, 170, 71, 21))
        self.btnChooser.setObjectName(_fromUtf8("btnChooser"))
        self.comboCategory = QtGui.QComboBox(EditDlg)
        self.comboCategory.setGeometry(QtCore.QRect(130, 110, 261, 27))
        self.comboCategory.setObjectName(_fromUtf8("comboCategory"))
        self.label_8 = QtGui.QLabel(EditDlg)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 71, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))

        self.retranslateUi(EditDlg)
        QtCore.QObject.connect(self.btnOk, QtCore.SIGNAL(_fromUtf8("clicked()")), EditDlg.accept)
        QtCore.QObject.connect(self.btnExit, QtCore.SIGNAL(_fromUtf8("clicked()")), EditDlg.reject)
        QtCore.QObject.connect(self.btnOk, QtCore.SIGNAL(_fromUtf8("clicked()")), EditDlg.deleteLater)
        QtCore.QObject.connect(self.btnExit, QtCore.SIGNAL(_fromUtf8("clicked()")), EditDlg.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(EditDlg)

    def retranslateUi(self, EditDlg):
        EditDlg.setWindowTitle(QtGui.QApplication.translate("EditDlg", "增加/修改记录", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EditDlg", "标识数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EditDlg", "姓名", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EditDlg", "分类", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EditDlg", "价格", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("EditDlg", "图片", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EditDlg", "时间", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("EditDlg", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("EditDlg", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("EditDlg", "备注", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChooser.setText(QtGui.QApplication.translate("EditDlg", "选择文件", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("EditDlg", "进/出货", None, QtGui.QApplication.UnicodeUTF8))

